// Startup Intelligence variant - investor/startup product surface only.
import type { MapLayers, PanelConfig } from '@/types';
import type { VariantConfig } from './base';

export const DEFAULT_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Startup Context Map', enabled: true, priority: 1 },
  insights: { name: 'Investment Brief', enabled: true, priority: 1 },
  'top-vc-signals': { name: 'Highest-Conviction Signals', enabled: true, priority: 1 },
  startups: { name: 'Companies to Watch', enabled: true, priority: 1 },
  producthunt: { name: 'Launch Radar', enabled: true, priority: 1 },
  ai: { name: 'AI Observatory', enabled: true, priority: 1 },
  markets: { name: 'Public Comps', enabled: true, priority: 1 },
  'macro-signals': { name: 'Exit & Risk Window', enabled: true, priority: 1 },

  'live-news': { name: 'Live Dealflow Headlines', enabled: false, priority: 2 },
  vcblogs: { name: 'VC Thesis Library', enabled: false, priority: 2 },
  regionalStartups: { name: 'Ecosystem Radar', enabled: false, priority: 2 },
  unicorns: { name: 'Valuation Watch', enabled: false, priority: 2 },
  accelerators: { name: 'Demo Days & Accelerators', enabled: false, priority: 2 },
  ipo: { name: 'IPO & M&A Signals', enabled: false, priority: 2 },
  tech: { name: 'Tech Market Signals', enabled: false, priority: 2 },
  cloud: { name: 'Cloud & AI Infrastructure', enabled: false, priority: 2 },
  hardware: { name: 'Semiconductor & Hardware', enabled: false, priority: 2 },
  fintech: { name: 'Fintech Watch', enabled: false, priority: 2 },
  finance: { name: 'Market Context', enabled: false, priority: 2 },
  layoffs: { name: 'Talent & Layoff Signals', enabled: false, priority: 2 },
  policy: { name: 'AI Policy & Regulation', enabled: false, priority: 2 },
  security: { name: 'Cybersecurity Watch', enabled: false, priority: 2 },
  'tech-readiness': { name: 'Tech Readiness Index', enabled: false, priority: 2 },
  events: { name: 'Tech Events', enabled: false, priority: 2 },
  monitors: { name: 'Investment Monitors', enabled: false, priority: 2 },
};

export const STARTUP_PANEL_KEYS = Object.freeze(Object.keys(DEFAULT_PANELS));

export const DEFAULT_MAP_LAYERS: MapLayers = {
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  radiationWatch: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: true,
  cloudRegions: true,
  accelerators: true,
  techHQs: true,
  techEvents: true,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  gpsJamming: false,
  satellites: false,
  ciiChoropleth: false,
  resilienceScore: false,
  dayNight: false,
  miningSites: false,
  processingPlants: false,
  commodityPorts: false,
  webcams: false,
  diseaseOutbreaks: false,
};

export const MOBILE_DEFAULT_MAP_LAYERS: MapLayers = {
  ...DEFAULT_MAP_LAYERS,
  cloudRegions: true,
  techHQs: true,
  techEvents: true,
};

export const VARIANT_CONFIG: VariantConfig = {
  name: 'startup',
  description: 'Startup, VC, AI-stack, and market intelligence dashboard',
  panels: DEFAULT_PANELS,
  mapLayers: DEFAULT_MAP_LAYERS,
  mobileMapLayers: MOBILE_DEFAULT_MAP_LAYERS,
};
